name: gleap_http_interceptor
description: "Gleap Flutter HTTP interceptor for network logs in customer feedback and in-app bug reports."
version: 1.2.4
homepage: https://www.gleap.ai

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  http_interceptor: '>=1.0.2'
  gleap_sdk: '>=6.4.4'
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
